name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃 (Gradle Wrapper 포함)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 실행 권한 추가
        run: chmod +x gradlew

      - name: Gradle 빌드
        run: ./gradlew build